# Generated by Django 4.1.1 on 2022-11-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Max 255 character', max_length=255, verbose_name='First Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('company', models.TextField(blank=True, null=True, verbose_name='Company')),
                ('telephone', models.CharField(max_length=25, verbose_name='Telephone')),
                ('address_one', models.TextField(verbose_name='Address_one')),
                ('address_two', models.TextField(blank=True, null=True, verbose_name='Addres_two')),
                ('comment', models.TextField(verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
            },
        ),
        migrations.DeleteModel(
            name='about_us',
        ),
        migrations.DeleteModel(
            name='contact_us',
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='description',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='title',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='contact_information',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contact_information',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='updated_at',
        ),
    ]
