# Generated by Django 4.1.1 on 2022-11-08 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactinfo_delete_contact_information'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Contact Info', 'verbose_name_plural': 'Contact Info'},
        ),
    ]
