# Generated by Django 4.1.1 on 2022-11-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'reviews', 'verbose_name_plural': 'reviews'},
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='price_review',
            new_name='price_rating',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='quality_review',
            new_name='quality_rating',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='value_review',
            new_name='value_rating',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review',
            field=models.TextField(verbose_name='Review'),
        ),
    ]
