# Generated by Django 4.1.1 on 2022-11-08 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Max 255 character', max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(help_text='Max 255 character', max_length=50, verbose_name='Last Name')),
                ('company', models.TextField(verbose_name='Company')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('address', models.TextField(verbose_name='Street Address')),
                ('country', django_countries.fields.CountryField(max_length=255, verbose_name='Country')),
                ('telephone', models.CharField(max_length=25, verbose_name='Telephone')),
                ('fax', models.CharField(max_length=50, verbose_name='Fax')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Checkout Billing',
                'verbose_name_plural': 'Checkout Billings',
            },
        ),
        migrations.CreateModel(
            name='CheckoutShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Max 255 character', max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(help_text='Max 255 character', max_length=50, verbose_name='Last Name')),
                ('company', models.TextField(verbose_name='Company')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('address', models.TextField(verbose_name='Street Address')),
                ('country', django_countries.fields.CountryField(max_length=255, verbose_name='Country')),
                ('telephone', models.CharField(max_length=25, verbose_name='Telephone')),
                ('fax', models.CharField(max_length=50, verbose_name='Fax')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Checkout Shipping',
                'verbose_name_plural': 'Checkout Shipping',
            },
        ),
        migrations.RenameModel(
            old_name='shopping_cart',
            new_name='ShoppingCart',
        ),
        migrations.DeleteModel(
            name='Ckeckout_billing_info',
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': 'Shopping Cart', 'verbose_name_plural': 'Shopping Cart'},
        ),
    ]
